### ISSUE TITLE
Script not working on flameshot v11

### ISSUE THREAD

**Issue by sukalaper** [berrabe/awesome-flameshot#2]
Hello, Berrabe!

sorry in advance for my bad english.
I had a problem using your script when I updated flameshot to v.11. everything is not showing up, new images are not detected either.
any suggestions for me? oh, yeah I'm not a coder, thanks.

**Comment by berrabe** [comment]
"new images are not detected", are you sure that flameshot and awesome-flameshot output / screenshot directory already in the same folder?

**Comment by sukalaper** [comment]
Hello, I am happy for a fast response.
Here I give a little of your source:
> _SCREENSHOT_DIR_=$HOME/Pictures
_LOG_FILE_="$_SCREENSHOT_DIR_/.awesome-flameshot.log"

everything seems to be running on Flameshot v0.10.2 

but... 
when i update to the newest flameshot, your script is not working and there is no any log from .awesome-flameshot.log
>  [+] SCRENSHOTING 
  |--[+] Starting Flameshot ...................... [ Success ] 
  |--[+] Checking Latest Image ................... [ No New Image Detected ] 


# NOTE :
after reading the [latest features of flameshot](https://github.com/flameshot-org/flameshot/releases), I found that:

> A config file checker has been implemented. If your config file contains error it will prompt to on how to fix them.

> Some config file semantics changed so when you first run version 11, it is likely you need to resolve the config file errors. We try not to break the semantics of this file but some times we need to

as far as I've seen&done, when using the latest flameshot, we have to do 2x shots and then your script will execute the image that was captured via the first flameshot.
for troubleshooting this time, I decided to re-build ((because yay also seems to be having problems.))
Thanks, Berrabe!

**Comment by berrabe** [comment]
I've tried awesome-flameshot w/ flameshot v11, and I found a way to make this work by removing the "--raw" params on line 163

NOTE: this method only applies to flameshot version 11, most likely this is because of a bug from flameshot, because how "--raw" work in v10 and v11 is different
